### ISSUE TITLE
Objectives

### ISSUE THREAD

**Issue by meyesydn** [sajalshres/sta-518-project#3]
https://github.com/sajalshres/sta-518-project/blob/a2ebea091f2d1044b069126a6e496626cec25f2d/README.md?plain=1#L9

Once again, very cool topic! I am more curious do you plan on making a simulator where you can compare any neighborhood and its the users choice or if you are analyzing it and reporting information. I think both could be cool to look at!

**Comment by sajalshres** [comment]
Partially implemented in map widget. Marking as complete.
