### ISSUE TITLE
The data others will access

### ISSUE THREAD

**Issue by scholln** [sajalshres/sta-518-project#4]
https://github.com/sajalshres/sta-518-project/blob/a2ebea091f2d1044b069126a6e496626cec25f2d/README.md?plain=1#L7

I love the idea of getting more insight into this, I feel as if this was an untapped resource for a while.  Would the others accessing the API be getting the raw data or the analysis that you came up with?  I think an interactive analysis tool would be helpful in this case.

**Comment by sajalshres** [comment]
Hi @scholln 

I planning to create endpoints for both raw data and analysis. It could be something like:

**Raw Data** Endpoint:
`/api/v1/raw/country/usa/city/chicago/listings`

**Analysis** Endpoint:
`/api/v1/analyse/compare-neighborhoods?country=usa&city=chicago`

**Comment by sajalshres** [comment]
Implemented. Marking as complete.
