### ISSUE TITLE
Google Trends

### ISSUE THREAD

**Issue by BrookemWalters** [sajalshres/sta-518-project#5]
https://github.com/sajalshres/sta-518-project/blob/a2ebea091f2d1044b069126a6e496626cec25f2d/README.md?plain=1#L14

If it makes sense within the scope of your project, search engine optimization (SEO) is worth a look. Under "related queries" 

 [Google Trends](https://trends.google.com/trends/explore?q=air%20bnb&geo=US) allows you to see the top searched-for words around certain categories, which is helpful for creating online listings.

**Comment by sajalshres** [comment]
Partially implemented SEO using meta tags in html renders. Great idea. 👍
