### ISSUE TITLE
neighborhoods within cities 

### ISSUE THREAD

**Issue by mcilvaiv** [sajalshres/sta-518-project#6]
https://github.com/sajalshres/sta-518-project/blob/a2ebea091f2d1044b069126a6e496626cec25f2d/README.md?plain=1#L20
I am not super familiar with Chicago but I wonder if there are different neighborhoods within the city like there are in New York. If this is the case, I think it could be cool to do comparisons within neighborhoods and between neighborhoods.

**Comment by sajalshres** [comment]
Marking as complete.
